apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-echigoya
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mychart
  template:
    metadata:
      labels:
        app: mychart
    spec:
      containers:
        - name: hello-echigoya
          image: 226104789339.dkr.ecr.ap-northeast-1.amazonaws.com/hello-echigoya:{{ .Values.imgv }}
          ports:
            - containerPort: 5042
