apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
       - name: jenkins
         image: jenkins/jenkins:lts
         ports:
          - containerPort: 8080
            name: default
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080