apiVersion: v1
kind: Service
metadata:
  name: hello-echigoya
  namespace: {{ .Values.targetnamespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5042
      protocol: TCP
  selector:
    app: mychart
