apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 100
  namespace: argocd
spec:
  project: 100
  source:
    repoURL: 'https://github.com/himiyauchi/echigoya-k8s-manifest.git'
    path: test-helm
    targetRevision: 'feature-100'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
