apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: 100
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: feature-100 project
  sourceRepos:
    - "*"
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
